config/routes.rb
RecipeSite::Application.routes.draw do
  
  get "errors/server_error"
  get "errors/not_found"
  get "/recipe/search" => "recipe#search_index"
  resources :recipe, :except => [:index]
  resources :favorite
  resources :ingredient
  resources :recipe_ingredient
  
  get "/profile" => "profile#show"
  resources :profile
  
  
  get "/login" => "user#login"
  get "/profile/update" => "profile#update"
  get "/profile/:id" => "user#profile"
  post "/recipe/:id/fav" => "favorite#fav_recipe"
  post "/recipe/:id/unfav" => "favorite#unfav_recipe"

  get "/api/list" => "api#get_recipes"
  get "/api/find/:id" => "api#get_recipe"
  
  root 'recipe#search_index'
  
  get "/auth/:provider/callback", to: "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  
  get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :recipe_ingredients, :dependent => :destroy
  has_many :ingredients, :through => :recipe_ingredients
  has_many :recipe_images, :dependent => :destroy
  accepts_nested_attributes_for :recipe_ingredients
  accepts_nested_attributes_for :recipe_images
  belongs_to :user
  
  require "net/http"
  require "uri"
  require 'json'

  
  def self.get_request_url(full_path, host_path)
    full_path.gsub("http://"+host_path, "")
  end
  
  def self.get_search_recipes(params)
    
    recipe_db_hash_list = [] #List used to store db recipe hashes
    recipe_yummly_hash_list = [] #List used to store yummly recipe hashes
    recipeList = get_recipes_from_db(params) #All recipes from DB
    
    params_page = params[:new_page] ? params[:new_page] : 0
    page = params_page.to_i / 12      #0 = first page, 1,2,n rest pages
    pagesInDB = (recipeList.count / 12).floor #Get the number of pages that the db recipes will generate
    offset = recipeList.count % 12 #How many recipes we have to get from elsewhere
      
    total_yummly_hash = get_yummly_hash(params, page, pagesInDB, offset) #Get the number of yummmly hashes
    yummly_list = total_yummly_hash['matches']   #Get the list of recipes from yummly
    
    #Create hash from recipes from DB and insert into db_hash_list
    recipeList.each { |recipe|
      unless recipe.blank?
        recipe_hash = {
          "id" => recipe.id,
          "recipeName" => recipe.recipeName,
          "imageUrls" => [],
          "totalTimeInSeconds" => recipe.totalTimeInSeconds,
          "rating" => recipe.rating,
          "ingredients" => [] 
        }
        
        recipe.recipe_images.each {|img| recipe_hash['imageUrls'].push(img.image_url)}
        recipe.ingredients.each {|ing| recipe_hash['ingredients'].push(ing)}
        
        recipe_db_hash_list.push(recipe_hash)
      end
    }

    #Create hash for each recipe from Yummly, and inserting into yummly_hash_list
    yummly_list.each { |recipe|
        recipe_hash = {
          "id" => recipe['id'],
          "recipeName" => recipe['recipeName'],
          "imageUrls" => [recipe['smallImageUrls'].first],
          "totalTimeInSeconds" => recipe['totalTimeInSeconds'],
          "rating" => recipe['rating'],
          "ingredients" => [] 
      }
      recipe['ingredients'].each {|ing| recipe_hash['ingredients'].push(ing)}
      recipe_yummly_hash_list.push(recipe_hash)
    }
    
    #The final list that only shall show 12 recipes
    presentation_list = recipe_db_hash_list[page*12, (page*12)+12]
    
    #If the list is nil, it is no recipes from the DB in it
    if presentation_list.nil?
      presentation_list = recipe_yummly_hash_list
    elsif presentation_list.count < 12 #If there is ex only 2 recipes from db, insert 10 from yummly
      presentation_list = presentation_list.concat(recipe_yummly_hash_list)
    end
        
    #The final hash that is sent to view
    final_recipe_hash = {
        "totalMatchCount" => "",
        "matches" => []      
    }

    #Insert the list of all recipes for given page, and set total number of recipes found
    final_recipe_hash['matches'] = presentation_list
    final_recipe_hash['totalMatchCount'] = (total_yummly_hash['totalMatchCount'].to_i + recipeList.count).to_s
    return final_recipe_hash
  end  
    
  def self.get_recipes_from_db(params)
    finalRecipeList = []
    recipeList = []
    ingredientList = []
    search_string = params[:search_string]
    puts params[:search_string]
    
    if search_string.include? ";"
      search_string_array = search_string.split(/;\s*/)
      recipeName = search_string_array[0].to_s
      Recipe.where('recipeName LIKE ?', '%'+recipeName+'%').each {|r| recipeList.push(r) }
      search_string = (search_string_array[1] != nil) ? search_string_array[1] : ""
    end
    
    ingredientList = search_string.squish.split(/,\s*/) 

    if ingredientList.blank? && !recipeList.blank?
      recipeList.each {|rec| finalRecipeList.push(rec)}
    else    
      #If there is a recipes found with name, see if it contains all search ingredients
      if !recipeList.blank? 
        recipeList.each do |rec|
          if recipe_contain_ingredients(rec, ingredientList)
            finalRecipeList.push(rec)
          end
        end #Each end
      end #Blank? end
      
      #Check all recipes and find them who contain all ingredients
      Recipe.all.each do |rec|
        if recipe_contain_ingredients(rec, ingredientList)
          finalRecipeList.push(rec)
        end
      end #each end
    end #ingredientList.blank? && !recipeList.blank? END    
    
    return finalRecipeList.uniq
  end
  
  def self.recipe_contain_ingredients(rec, ingredList)
    counter = 0
    
    ingredList.each do |ingred| #Loop through all the search ingredients
      rec.ingredients.each do |rIngred| #Loop through all ingredients in given recipe
        if rIngred.title.casecmp(ingred) == 0 #Recipe ingredient and search ingredient matches
          puts ingred + " equals " + rIngred.title
          counter += 1
        end
      end
    end
    
    if counter >= ingredList.count #If 2 ingredients are searched for, recipe need to contain both
      return true
    else 
      return false
    end    
  end
  
  def self.get_yummly_hash(params, requestPage, pagesInDB, offset)
    if pagesInDB >= requestPage
      return get_recipes_from_api(params, 0, (12-offset) == 0 ? 1 : (12-offset))
    else
      start_at = ((requestPage - pagesInDB) *12) - offset
      return get_recipes_from_api(params, start_at, 12)
    end
  end
  
  def self.get_recipes_from_api(params, start, max_result)
        
    apiAuthString = "http://api.yummly.com/v1/api/recipes?_app_id="+ENV['APP_ID']+"&_app_key="+ENV['APP_KEY']
    apiSearchString = ""
    
    if params[:search_string]
      apiSearchString += getAPISearchString(params[:search_string])
    end
    
    if params[:checked_cuisines]
      apiSearchString += getAllowedCuisineString(params[:checked_cuisines])
    end
    
    if params[:max_minutes].to_i > 0
      apiSearchString += "&maxTotalTimeInSeconds="+(params[:max_minutes].to_i * 60).to_s
    end
    
    #Smart if/else sentence, if it has params set start to that value, else start on 0   
    apiSearchString += "&maxResult="+max_result.to_s+"&start="+ start.to_s
    puts apiSearchString  

    uri = URI.parse(apiAuthString+apiSearchString)
    # Shortcut
    response = Net::HTTP.get_response(uri)
    # Will print response.body
    Net::HTTP.get_print(uri)
    # Full
    http = Net::HTTP.new(uri.host, uri.port)
    response = http.request(Net::HTTP::Get.new(uri.request_uri))
    parsed = JSON.parse(response.body)
  end

  def self.getAPISearchString(search_string)
    allowedIngredientString = ""
    
    if search_string.include? ";"
      newlist =  search_string.split(/;\s*/)
      allowedIngredientString += "&q="+newlist[0].to_s.gsub(" ", "+")
      search_string = (newlist[1] != nil ? newlist[1] : "")
    end
    
    #Remove all newlines, and long spaces, then split string into array with each ingredient
    search_string.squish.split(/,\s*/).each do |ingred|
      allowedIngredientString += "&allowedIngredient[]="+ingred
    end
    return allowedIngredientString
  end
  
  def self.getAllowedCuisineString(cuisines)
    includeCuisineString = ""
    cuisines.each do |key, value|
      includeCuisineString += "&allowedCuisine[]=cuisine%5Ecuisine-"+value.downcase
    end
    return includeCuisineString 
  end

  def self.get_recipe_from_api(id)
    apiAuthString = "http://api.yummly.com/v1/api/recipe/"+id+"?_app_id="+ENV['APP_ID']+"&_app_key="+ENV['APP_KEY']
    uri = URI.parse(apiAuthString)
    # Shortcut
    response = Net::HTTP.get_response(uri)
    # Will print response.body
    Net::HTTP.get_print(uri)
    # Full
    http = Net::HTTP.new(uri.host, uri.port)
    response = http.request(Net::HTTP::Get.new(uri.request_uri))
    parsed = JSON.parse(response.body)
    
    recipeHash = {
        "id" => parsed['id'], 
        "recipeName" => parsed['name'],
        "rating" => parsed['rating'],
        "totalTimeInSeconds" => parsed['totalTimeInSeconds'],
        "images" => [parsed['images'][0]['hostedLargeUrl']],
        "ingredients" => [],
        "source" => "yummly",
        "created_by" => {
                    "id" => "",
                    "name" => parsed['source']['sourceSiteUrl']
                },
        "description" => parsed['source']['sourceRecipeUrl']
      }
      parsed['ingredientLines'].each { |line| 
          line_list = splitIngredientLine(line)
          puts line
          ingredient_hash = {}
          if line_list.size > 3
            ingredient_hash = { 
                            "amount" => line_list[1], 
                            "unit" => line_list[2],
                            "name" => line_list[3]
                             }
          elsif line_list.count == 1 #If there is only a name, for example: bacon bits
              ingredient_hash = { 
                          "amount" => nil, 
                          "unit" => nil,
                          "name" => line_list[0]
                           }
          else
             ingredient_hash = { 
                          "amount" => line_list[1], 
                          "unit" => nil,
                          "name" => line_list[2]
                           }
          end
          recipeHash['ingredients'].push(ingredient_hash)
      }
      return recipeHash
    
  end
  
  def self.splitIngredientLine(line)
    units = [
            'cup',
            'quart',
            'gallon',
            'pound',
            'pint',
            'ounce' ]
    
    joined_units = (units.collect{|u| u.pluralize} + units).join('|')
    ingredientList  = line.split(/([\d\/\.\s]+(\([^)]+\))?)\s(#{joined_units})?\s?(.*)/i)
  end
  
  def self.get_recipe_hash(recipe)
      recipeHash = {
        "id" => recipe.id, 

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  respond_to :xml, :json, :html
  def index
    if current_user
      @recipes = current_user.recipes
      respond_with(@recipe)
    else
      require_login
    end 
  end
  
  def search_index
    @cuisineList = ['American', 'Italian', 'Asian', 'Mexican', 'French', 'Southwestern', 'Barbecue', 'Indian', 'Chinese', 'English', 'Mediterranean', 'Greek', 'Spanish', 'German', 'Thai', 'Moroccan', 'Irish', 'Japanese', 'Cuban', 'Hawaiin', 'Swedish', 'Hungarian', 'Portugese']
    
    #If user wants to change page insearch result
    if params[:new_page]
      @startat = params[:new_page]
      params.merge!(session[:search_params])
      params[:new_page] = @startat
    end
    
    unless params[:search_string].blank?
      #Only change request url if the user does a new search, and not on page change
      if params[:new_page].blank?
        @requesturl = Recipe.get_request_url(request.url,request.env['HTTP_HOST'])
      else
        @requesturl = session[:search_url]
        session[:search_url] = nil
      end
      
      @recipeResult = Recipe.get_search_recipes(params)
      @search_word = params[:search_string]
      session[:search_params] = params
      session[:search_url] = @requesturl
      respond_to do |format|
      format.html { }
        format.js   {}
      end
    end
  end
  
  def show
    begin
      if Recipe.where("id = ?", params[:id]).blank?
        @recipe = Recipe.get_recipe_from_api(params[:id])
      else
        @dbRecipe = Recipe.find(params[:id])
        @recipe = Recipe.get_recipe_hash(@dbRecipe)
      end
  
      if current_user
        @is_favorite = Favorite.check_if_favorite(@recipe['id'], current_user)
      end
      respond_with(@recipe)
    rescue => ex
      logger.error ex.message
      redirect_to :root
    end
  end
  
  def new     #GET /recipe/new
    if current_user
      @recipe = Recipe.new
      @recipe.recipe_ingredients.build
      @ingredients = Ingredient.all
      @new_ingredient = Ingredient.new
    else
      require_login
    end
  end

  def create  #POST /recipe
    begin 
    @recipe = Recipe.new(recipe_params)

    # Add the user id
    if current_user; @recipe.user_id = current_user.id end

    # Ingredients hash in params
    if params['ingredients']
      is = params['ingredients']
      is.each do |k,v|
  
        # Neede params
        amount = v['amount']
        unit = v['unit']
        ingredient_id = v['ingredient_id'].to_i
  
        # Only add the recipe_ingredient if the ingredient exists
        if Ingredient.exists?(ingredient_id)
          # Make a new recipe_ingredient
          ingredient = Ingredient.find(ingredient_id)
          recipe_ingredient = RecipeIngredient.new(
            amount: amount,
            unit: unit,
            ingredient: ingredient
            )
  
          # Add it to the recipe
          @recipe.recipe_ingredients.push(recipe_ingredient)
        end
      end
    end

    # Image url
    if params['image_url']
      @recipe.recipe_images.new(:image_url => params['image_url'])
    end

    if @recipe.save
      redirect_to @recipe
    else
      render "new"
    end
    rescue => ex
      logger.error ex.message
      redirect_to :root
    end
  end

  def destroy #DELETE /recipe/:id
    if current_user
      @recipe = Recipe.find(params[:id])

      if @recipe.user_id == current_user.id
        if !Favorite.where("source_id = ?", @recipe.id).blank?
          Favorite.destroy(Favorite.where("source_id = ?", @recipe.id))
        end
        @recipe.destroy
      end

      redirect_to "/profile"
    else
      require_login
    end
  end

  
  def update  #PUT/PATCH /recipe/:id
    if current_user

      @recipe = Recipe.find(params[:id])

      if @recipe.update(recipe_params)
        redirect_to @recipe
      else
        render "edit"
      end
    else
      require_login
    end
  end

  def edit    #GET /recipe/:id/edit
    @recipe = Recipe.find(params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(
      :recipeName,
      :description,
      :totalTimeInSeconds,
      ingredients: [
        :amount,
        :unit,
        :ingredient_id
      ],
      recipe_ingredients_attributes: [
        [
          :amount,
          :unit,
          :id
        ]
      ],
      recipe_images_attributes: [
        [
          :image_url,
          :id
        ]
      ]
      #,ingredients: [:name, :description]
      )
  end  
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/recipe/_ingredient_list.html.erb
<table>
  <% @ingredients.each do |ingredient| %>
    <tr id="ingredient_<%= ingredient.id %>"
      data-ingredient-id="<%= ingredient.id %>"
      data-ingredient-title="<%= ingredient.title %>"
      data-ingredient-description="<%= ingredient.description %>"
      class="ingredient_row hidden"
    >
      <td>
        <%= ingredient.title %>
      </td>
      <td>
        <%= ingredient.description %>
      </td>
      <td>
        <a href="#"> <i class="fa fa-plus-circle"></i> </a>
      </td>
    </tr>
  <% end %>
</table>
<a id="show-create-ingredient" href="#create-ingredient" rel="facebox">Add new ingredient</a>

app/views/recipe/_recipe_list.html.erb
<div class="row-fluid" id="recipe-result-body">
	<% if @recipeResult %>
	<div class="recipe-result-label"> Recipes found:  <span class="label label-info"><%= @recipeResult['totalMatchCount'] %> </span></div>
	<div id="recipe-pagination" data-page-number="<%= @recipeResult['totalMatchCount'] %>"></div>
	<div id="request-url" style="display: none;"> <%= @requesturl %> </div>
	
    <div class="flex-container-results">
    <% @recipeResult['matches'].each do |rb| %>
    <div class="recipe-list-item-parent" onmouseover="this.style.cursor='pointer'"
                        onclick="DoNav('<%= recipe_path(rb['id'])%>')">
    	<div class="recipe-list-item-name">
    		<%= rb['recipeName'] %>
    	</div>
    	<div class="recipe-list-item-info-parent">
			<div class="recipe-list-item-image">
				<%= image_tag rb['imageUrls'].first, :size => "90x60"%> </br>
			</div>
			<div class="recipe-list-item-info">
				<i class="icon-time"></i> <%= (rb['totalTimeInSeconds'].to_i / 60).to_s %> Minutes </br>
				<i class="icon-star"></i> <%= rb['rating'].to_f %> / 6.0 </br>
				<a class="ingredients-link btn btn-warning btn-small disabled" title="Ingredients"><%= rb['ingredients'].length %> Ingredients
	                <div class="ingredients-well" style="display: none;">        
                        <ul>
                            <% rb['ingredients'].each do |ingred| %>
                            <li>
                                    <%= ingred %>
                            </li>
                            <%end%>
                        </ul>
	                </div> 
	            </a>
			</div>
		</div>
	</div>
	<%end%> 
	</div>
	<%end%>
	<% if @recipeResult && @recipeResult['matches'].empty?%>
		<h3> No results for &laquo<%= @search_word %>&raquo </h3>
	<%end%>
</div>

app/views/recipe/edit.html.erb
<h1>Edit recipe</h1>

<%= form_for(@recipe, {
            :url => {
            	# method on controller
              :action => "update" }

              # or url with http verb
							# :url => recipe_index_path,
							# :method => 'patch'
            }) do |f| %>

  <% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="recipe-edit_container">
    <div class="recipe-edit_primary">
      <p>
        <%= f.label :recipeName, 'Title' %><br>
        <%= f.text_field :recipeName %>
      </p>
      <p>
        <%= f.label :totalTimeInSeconds, 'Total time in seconds' %><br>
        <%= f.number_field :totalTimeInSeconds %>
      </p>
      <p>
        <%= f.label :description %><br>
        <%= f.text_area :description, class: 'new-recipe-description' %>
      </p>

      
      <div class="recipe-edit_submit">
        <p>
        <%= f.label :Images, 'Url to image' %><br>

        <% @recipe.recipe_images.each do |recipe_image| %>
          <%= f.fields_for :recipe_images, recipe_image do |recipe_image_fields| %>
            <%= recipe_image_fields.text_field :image_url %>
          <% end %>
        <% end %>
        </p>
       
        <p>
          <%= f.submit :class => 'btn btn-success' %>
        </p>
      </div>
    </div>


    <div class="recipe-edit_secondary clearfix">
      <p>
        Ingredients

        <table>
          <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
            <%= f.fields_for :recipe_ingredients, recipe_ingredient do |recipe_ingredient_fields| %>
              <tr>
                <td>
                  <strong><%= recipe_ingredient.ingredient.title %>: </strong>
                </td>
                <td>
                  <%= recipe_ingredient_fields.text_field :amount, :class => 'input-small' %>
                  
                </td>
                <td>
                  <%= recipe_ingredient_fields.text_field :unit, :class => 'input-small'  %>
                  
                </td>
                <td>
                  <%= link_to 'Destroy', recipe_ingredient_path(recipe_ingredient.id),
                          method: :delete,
                          data: { confirm: "Are you sure?" } %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </p>
    </div>

  </div>
<% end %>

app/views/recipe/index.html.erb
<% if current_user == @user %>
	<%= button_to "Create new", new_recipe_path, :class => "btn btn-success", :method => :get %>
<%end%>

<% if @recipes.blank?%> 
	<h4> No recipes <i class="fa fa-frown-o"></i> </h4>
<%else%>
	<h4><%= @recipes.count %> <%= @recipes.count == 1 ? "Recipe" : "Recipes"%> </h4>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Name</th>
			</tr>
		</thead>
		<tbody>
			<% @recipes.all.each do |rec| %>
			<tr onmouseover="this.style.cursor='pointer'"
                        onclick="DoNav('<%= recipe_path(rec.id)%>')">
				<td> <%= rec.recipeName %></td>
			</tr>
			<%end%>
		</tbody>
	</table>
<%end%>

app/views/recipe/new.html.erb
<h1>Create Recipe</h1>

<%= form_for(@recipe, {
            :url => {
              :action => "create" }
            }) do |recipe_form| %>


  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section id="new_recipe" class="new-recipe">

    <section class="new-recipe_description span6">
      <p>
        <%= recipe_form.label :recipeName, 'Title' %>
        <%= recipe_form.text_field :recipeName %>
      </p><p>
        <%= recipe_form.label :totalTimeInSeconds, 'Total time in seconds' %>
        <%= recipe_form.number_field :totalTimeInSeconds %>
      </p>
      <p>
        <%= recipe_form.label :description %>
        <%= recipe_form.text_area  :description, :class=>'new-recipe-description clearfix'%>
      </p>
      <p>
        <%= recipe_form.label :Image, 'Url to Image' %>
        <%= text_field_tag :image_url %>
      </p>

      <p>
        <%= recipe_form.submit :class => "btn btn-success" %>
      </p>
    </section>


    <section class="new-recipe_ingredient-list">

      <%= recipe_form.label :Ingredients %>
      <table id="recipe_ingredients_list">
      </table>
      <input id="ingredient_title"
        placeholder="Add an ingredient"/>
      <div id="recipe_ingredients_list_popover" class="hidden">
        <section id="ingredients_list">
          <%= render :partial => 'ingredient_list' %>
        </section>
      </div>

    </section>


  

  </section>


<% end %>

<section id="create-ingredient" class="clearfix hidden">
  <h1>Create Ingredient</h1>

    <%= form_tag('/ingredient', :remote => true) do %>
      <p>
        <%= label_tag :title %><br>
        <%= text_field_tag :title %><br>

        <%= label_tag :description %><br>
        <%= text_field_tag :description %>
      </p>

      <p>
        <%= submit_tag 'Create', :class => "btn btn-success"  %>
      </p>
    <% end %>
</section>




<script id="ingredient_template" type="text/template">
    <tr id='recipe_ingredient_{ client_id }'>
      <td>
        <strong>{ ingredient_title }: </strong>
      </td>
      <td>
        <input id="ingredients_{ client_id }_amount"
          class="input-small"
          placeholder="amount"
          name="ingredients[{ client_id }][amount]"
          type="text" />
      </td>
      <td>
        <input id="ingredients_{ client_id }_unit"
          class="input-small"
          placeholder="unit"
          name="ingredients[{ client_id }][unit]"
          type="text"/>

        <input id="ingredients_{ client_id }_ingredient_id"
          name="ingredients[{ client_id }][ingredient_id]"
          type="hidden"
          value="{ ingredient_id }"/>
      </td>
      <td>
        <a href="#" data-destroy-id="recipe_ingredient_{ client_id }">Delete</a>
      </td>
    </tr>
</script>
<!-- To imitate with the template
<div id='add_ingredient_0'>
  amount: <input id="ingredients_0_amount" name="ingredients[0][amount]" type="text" />
  unit: <input id="ingredients_0_unit" name="ingredients[0][unit]" type="text" />
  ingredient: { ingredient_title }
  <input id="ingredients_0_ingredient_id" name="ingredients[0][ingredient_id]" type="hidden" />
</div> -->

app/views/recipe/search_index.html.erb
	<div class="search-box">
	<%= image_tag("search-header.png")%>
	<%= form_tag("/recipe/search", :class=>'form-inline', :id => 'search-form', :remote => true, :method => :get) do %>
		 <%= text_field_tag	'search_text' , nil,  :placeholder => 'Ex: Onion Soup; Onion, Milk, ....', :name => 'search_string', :class => 'input-xxlarge' %>
		 <%= button_tag "Search", :class => 'btn btn-primary', :name => nil %>
		 
		 <div id="search_settings_group">
		    <a class="dropdown" data-toggle="collapse" data-target="#search_settings" data-parent="#search_settings_group">Advanced settings <i class="icon-chevron-down"></i></a>
		    <div class="accordion-group" style="border: 0px;">
		        <div class="collapse indent" id="search_settings">     						
					<div class="search-advanced-box">
						<%= field_set_tag  "Max minutes",:class => "fieldset_title" do %>
							<%= number_field_tag 'minutes_text' , nil, in: 0...1001, :placeholder => 'Type in max minutes', :name => 'max_minutes', :class => 'input-large' %>
						<%end%>
					</div>	     
		        	<div class="search-advanced-box">
	        			<%= field_set_tag  "Choose Cuisines",:class => "fieldset_title" do %>		
			        		<% @cuisineList.each do |cuisine| %>
			        			<label class="checkbox">
					        		<%= check_box_tag 'checked_cuisines[cuisine_'+cuisine+']', cuisine, false  %>
					        		<%= cuisine %>
					        	</label>
							<%end%>
						<%end%>
		        	</div>
		    	</div>
			</div>
		 </div>
	<% end %> <!-- form_tag end--> 
</div>
<div id="cur-recipe-page" data-current-page="1"></div>
<%= link_to "Next Page", recipe_search_path(:new_page => ""), :remote => true, :hidden => true, :id => "change-page-link"%>
<%= render :partial => "recipe/recipe_list" %>

app/views/recipe/search_index.js.erb
$("#recipe-result-body").empty();
$("<%= escape_javascript(render :partial => "recipe/recipe_list") %>").appendTo("#recipe-result-body");
window.listenToRecipe()
var url = document.getElementById('request-url').innerHTML
localStorage.setItem(url, document.getElementById('recipe-result-body').innerHTML)
history.pushState({search_url: url}, "Search Result", url)