config/routes.rb
RecipeSite::Application.routes.draw do
  
  get "errors/server_error"
  get "errors/not_found"
  get "/recipe/search" => "recipe#search_index"
  resources :recipe, :except => [:index]
  resources :favorite
  resources :ingredient
  resources :recipe_ingredient
  
  get "/profile" => "profile#show"
  resources :profile
  
  
  get "/login" => "user#login"
  get "/profile/update" => "profile#update"
  get "/profile/:id" => "user#profile"
  post "/recipe/:id/fav" => "favorite#fav_recipe"
  post "/recipe/:id/unfav" => "favorite#unfav_recipe"

  get "/api/list" => "api#get_recipes"
  get "/api/find/:id" => "api#get_recipe"
  
  root 'recipe#search_index'
  
  get "/auth/:provider/callback", to: "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  
  get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipe_ingredients, :dependent => :destroy
  has_many :recipes, :through => :recipe_ingredients
  
  def to_s
    "#{self.title}"  
  end
  
end

app/controllers/ingredient_controller.rb
class IngredientController < ApplicationController
	respond_to :xml, :json, :html

	def index		#GET /ingredient
		@ingredient = Ingredient.all
		respond_with(@ingredient)
	end

	def create	#POST /ingredient
		@ingredient = Ingredient.new(ingredient_params)

		if @ingredient.save
			@ingredients = Ingredient.all
			respond_to do |format|
				format.js
			end
		else
			render "new"
		end
	end

	def new			#GET /ingredient/new
		@ingredient = Ingredient.new
	end
	
	def edit		#GET /ingredient/:id/edit
		@ingredient = Ingredient.find(params[:id])
	end
	
	def show		#GET /ingredient/:id
		@ingredient = Ingredient.find(params[:id])
	end

	def update  #PUT/PATCH /ingredients/:id
		if current_user
			@ingredient = Ingredient.find(params[:id])
			if @ingredient.update(ingredient_params)
					redirect_to @ingredient
			else
					render 'edit'
			end
		else
			require_login
		end
	end


  private
  
  def ingredient_params
		params.permit(:title, :description)
  end
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/views/ingredient/create.js.erb
var $ingredients_list = $('#ingredients_list')
$ingredients_list.empty()
$("<%= escape_javascript( render :partial => "recipe/ingredient_list") %>").appendTo($ingredients_list)
window.get_ingredient_list()
$(document).trigger('close.facebox')

app/views/ingredient/edit.html.erb
<h1>Edit Ingredient</h1>

<%= form_for(@ingredient, {
            :url => {
            	# method on controller
              :action => "update" }

              # or url with http verb
							# :url => user_index_path,
							# :method => 'patch'
            }) do |f| %>

  <% if @ingredient.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>
    <ul>
    <% @ingredient.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>


  <p>
    <%= f.label :Title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :Description %><br>
    <%= f.text_field :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/ingredient/index.html.erb
<h1>Ingredient index page</h1>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
		<% @ingredient.all.each do |ingredient| %>
		<tr>
			<td> <%= ingredient.title %> </td>
			<td> <%= ingredient.description %> </td>
			<td>
				<%= link_to 'Show', ingredient_path(ingredient) %>
				<span> | </span>
				<%= link_to 'Edit', edit_ingredient_path(ingredient) %>
				<span> | </span>
				<%= link_to 'Destroy', ingredient_path(ingredient),
												method: :delete,
												data: { confirm: "Are you sure?" } %>
			</td>
		</tr>
		<%end%>
	</tbody>
</table>
<%= link_to 'Create ingredient', new_ingredient_path %>

app/views/ingredient/new.html.erb
<h1>Create Ingredient</h1>

<%= form_for(@ingredient, {
            :url => {
              :action => "create" }
            }) do |f| %>

  <% if @ingredient.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>
    <ul>
    <% @ingredient.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>

    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back", ingredient_index_path %>

app/views/ingredient/show.html.erb
<h1>Ingredient</h1>

<table>
	<tr>
		<td>
			title:
		</td>
		<td>
			<%= @ingredient.title %>
		</td>
	</tr>
	<tr>
		<td>
			description:
		</td>
		<td>
			<%= @ingredient.description %>
		</td>
	</tr>
</table>

<%= link_to "Back", ingredient_index_path %>